#!/usr/bin/zsh
# Post image right user
curl --data-urlencode json@image.json http://localhost:8080/asmoe16/mvc/public/api/pictures/user/2
# Post image wrong user
curl --data-urlencode json@image.json http://localhost:8080/asmoe16/mvc/public/api/pictures/user/1
# Post not an image
curl --data-urlencode json='{
"username" : "user2",
"password" : "User2User2",
"title" : "Not an image",
"description" : "This is not an image",
"image" : "'"$(cat ../mvc/app/controllers/ApiController.php | base64)"'"
}' http://localhost:8080/asmoe16/mvc/public/api/pictures/user/2
#Get users
curl -sG http://localhost:8080/asmoe16/mvc/public/api/users | jq
#Get image
curl -sG http://localhost:8080/asmoe16/mvc/public/api/pictures/user/1 | jq | less
#Proof get image works
curl -sG http://localhost:8080/asmoe16/mvc/public/api/pictures/user/2 | jq -r '.[0].image' | base64 -d >> New.jpg
